services:
  postgres:
    image: postgres:16
    container_name: socialmusic_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: socialmusic
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - musicapp-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: musicapp-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - musicapp-network

networks:
  musicapp-network:
    driver: bridge

volumes:
  postgres_data: